import assert from "node:assert/strict";
import { FingerStyring } from "./styring.js";

const input = new FingerStyring();
assert.ok(input.begyndGå(17));
assert.ok(input.begyndKig(23, 200, 300));
assert.equal(input.begyndGå(99), false, "En tredje finger overtager ikke gå-pinden");
assert.equal(input.begyndKig(99, 0, 0), false, "En tredje finger overtager ikke kameraet");
input.flytGå(17, 0, -18);
assert.equal(input.gang.y, .5, "En halv pindbevægelse giver halv fart");
input.flytGå(17, 90, -90);
assert.ok(Math.abs(Math.hypot(input.gang.x, input.gang.y) - 1) < 1e-9, "Diagonal bevægelse bliver ikke hurtigere");
assert.equal(input.flytGå(99, 0, 0), false);
assert.deepEqual(input.flytKig(23, 212, 291), { x: 12, y: -9 });
assert.equal(input.flytKig(17, 0, 0), null, "Gå-fingeren drejer ikke kameraet");
assert.equal(input.slipGå(99), false);
assert.ok(input.slipGå(17));
assert.deepEqual(input.flytKig(23, 218, 295), { x: 6, y: 4 }, "Kameraet fortsætter efter venstre hånd slippes");
assert.equal(input.gang.y, 0);
input.begyndGå(18);
input.flytGå(18, 0, -36);
assert.ok(input.slipKig(23));
assert.equal(input.gang.y, 1, "Gå-fingeren fortsætter efter højre hånd slippes");
input.flytGå(18, 1, 1);
assert.equal(input.gang.x, 0, "Centrum har et roligt dødt felt");
input.nulstil();
assert.deepEqual(input.gang, { x: 0, y: 0, id: null }, "Pause fjerner hele den holdte gå-finger");
assert.equal(input.kig, null);
assert.equal(input.flytGå(18, 0, -36), false, "En gammel pointer flytter ikke efter pause");
assert.ok(input.begyndKig(24, 1, 1), "En ny kamerafinger kan starte efter pause");
input.trykPil(31, "frem");
input.trykPil(32, "frem");
input.trykPil(33, "højre");
input.slipPil(31);
assert.equal(input.gårMod("frem"), true, "En pil bliver holdt, indtil dens sidste finger slippes");
input.slipPil(32);
assert.equal(input.gårMod("frem"), false);
assert.equal(input.gårMod("højre"), true, "Andre holdte pile er uafhængige");
assert.equal(input.trykPil(99, "hop"), false);
input.nulstil();
assert.equal(input.gårMod("højre"), false, "Pause fjerner også alle piletaster på touch");
input.trykTast("w");
assert.ok(input.taster.has("w"));
input.nulstil();
assert.equal(input.trykTast("w", true), false, "En tast holdt over pausen må først starte efter et nyt tryk");
assert.equal(input.taster.has("w"), false);
assert.ok(input.trykTast("w"));
assert.ok(input.trykTast("w", true), "En aktiv gå-tast må fortsat gentage");
console.log("Fingerstyring: samtidige hænder, ejerskab, fart, dødt felt og pause bestået.");
