// ===== Banerne i Rulle Rasmus =====
// Hver bane er en liste af stykker, der lægges efter hinanden (se bane.js for alle muligheder).
//   sving: grader (+ = højre, − = venstre) · r: radius i meter · lige: meter · hul: et hop over ingenting
//   bakke: op/ned · rampe: hop-rampe · bølger: [højde, antal] · rende: kanterne går op, så Rasmus holdes inde
//   kant: rækværk · flag: genstart her · mål: målstregen · frugt/puder/trampolin/fart: ting på banen
// Banen starter med standardværdierne øverst (bredde, rende, kant). fart: tophastighed (1 = normal).
// tema: se temaer.js · frø: tal der bestemmer, hvor pynten står

export const BANER = [
  {
    id: "engen", navn: "Engen", ikon: "🌼", tema: "eng", frø: 3,
    bredde: 7, rende: 0.35, kant: true, fart: 0.8,
    stykker: [
      { lige: 12 },
      { sving: 40, r: 18 },
      { lige: 8, bakke: -1.2 },
      { sving: -60, r: 14 },
      { lige: 6, flag: true },
      { lige: 10, puder: [0] },
      { sving: 70, r: 13, rende: 0.9 },
      { lige: 12, bølger: [0.6, 2], rende: 0.5, frugt: -1.5 },
      { sving: -50, r: 16, flag: true },
      { lige: 10, kant: false, bakke: -1.5 },
      { sving: 45, r: 16, kant: false },
      { lige: 8, bakke: 1 },
      { sving: -35, r: 18, flag: true },
      { lige: 10, frugt: 1.5 },
      { lige: 6, mål: true, bredde: 8.5 },
      { lige: 12 },
    ],
  },
  {
    id: "slik", navn: "Slikbanen", ikon: "🍭", tema: "slik", frø: 5,
    bredde: 6, rende: 0.5, kant: true, fart: 0.9,
    stykker: [
      { lige: 10 },
      { sving: -60, r: 12 },
      { lige: 10, puder: [[0.3, -1.4], [0.75, 1.4]] },
      { sving: 90, r: 10, rende: 1.3 },
      { lige: 6, flag: true, rende: 0.5 },
      { lige: 12, bølger: [0.55, 3], frugt: 1.2 },
      { sving: -80, r: 11, bredde: 5, kant: false },
      { lige: 5, fart: true, kant: false },
      { lige: 10, bakke: -3, kant: false },
      { sving: 120, r: 12, rende: 1.4, flag: true, bredde: 6 },
      { lige: 5, trampolin: true, rende: 0.4 },
      { hul: 4.5, stjerner: true },
      { lige: 8, flag: true },
      { sving: -70, r: 13, kant: false, frugt: -1 },
      { lige: 10, bakke: -1.5, puder: [0] },
      { lige: 6, mål: true, bredde: 8 },
      { lige: 12 },
    ],
  },
  {
    id: "is", navn: "Isbanen", ikon: "❄️", tema: "is", frø: 9,
    bredde: 7, rende: 0.8, kant: true, fart: 0.9, is: true,
    stykker: [
      { lige: 10, is: false },
      { sving: 50, r: 16 },
      { lige: 10, bakke: -2 },
      { sving: -90, r: 12, rende: 1.4 },
      { lige: 8, flag: true },
      { lige: 14, bølger: [0.55, 3], kant: false, frugt: 0 },
      { sving: 180, r: 11, rende: 1.5, bakke: -3 },
      { lige: 6, flag: true, rende: 0.8 },
      { lige: 10, bredde: 5.5, rende: 0.5, kant: false },
      { sving: -70, r: 14, kant: true, rende: 1.1 },
      { lige: 8, puder: [[0.5, 0]], bredde: 7, rende: 0.8 },
      { sving: 60, r: 14, flag: true },
      { lige: 10, bakke: -1, frugt: 1.5 },
      { lige: 6, mål: true, bredde: 8.5, is: false },
      { lige: 12, is: false },
    ],
  },
  {
    id: "jungle", navn: "Junglen", ikon: "🌴", tema: "jungle", frø: 11,
    bredde: 5, rende: 0.25, kant: true, fart: 1,
    stykker: [
      { lige: 10 },
      { sving: 45, r: 14 },
      { lige: 8, kant: false },
      { sving: -45, r: 14, flag: true },
      { lige: 4, fart: true },
      { lige: 5, rampe: 1.0, kant: false },
      { hul: 4.5, bakke: -1.2 },
      { lige: 8, bredde: 6, flag: true },
      { sving: 90, r: 11, rende: 0.9 },
      { lige: 10, bølger: [0.4, 3], kant: false, rende: 0.3, frugt: 1 },
      { lige: 4, trampolin: true, bredde: 5 },
      { hul: 4.5, bakke: 1 },
      { lige: 8, flag: true },
      { sving: -100, r: 12, rende: 1 },
      { lige: 12, bakke: -2, puder: [[0.3, -1.1], [0.7, 1.1]], rende: 0.3 },
      { lige: 6, mål: true, bredde: 7 },
      { lige: 12 },
    ],
  },
  {
    id: "regnbue", navn: "Regnbuen", ikon: "🌈", tema: "regnbue", frø: 13,
    bredde: 5, rende: 0.4, kant: false, fart: 1.05,
    stykker: [
      { lige: 10, kant: true },
      { sving: 60, r: 14, kant: true },
      { lige: 12, bølger: [0.6, 3] },
      { sving: -90, r: 12, rende: 1.2, flag: true },
      { lige: 4, fart: true, bredde: 5.5, rende: 0.3 },
      { lige: 5, rampe: 1.1 },
      { hul: 5.5, bakke: -1.5 },
      { lige: 8, flag: true, bredde: 5 },
      { sving: 120, r: 11, rende: 1.3, bakke: -2, kant: true },
      { lige: 12, bredde: 4, rende: 0.35, frugt: 0 },
      { sving: -60, r: 14 },
      { lige: 4, trampolin: true, bredde: 5 },
      { hul: 4.5 },
      { lige: 8, flag: true, bredde: 5.5 },
      { lige: 14, bakke: -4, bølger: [0.7, 2] },
      { lige: 6, mål: true, bredde: 8, kant: true },
      { lige: 12, kant: true },
    ],
  },
];
